import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Betting Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="container-fluid gradient-background min-h-screen flex justify-center">
        <div className="container static-background p-5">
            <h1>Your dashboard</h1>
        {children}

        </div>
    </div>
  );
}
